Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"

  config.vm.define "vagrant2" do |vagrant2|
    vagrant2.vm.box = "ubuntu/bionic64" 
    vagrant2.vm.hostname = "goapp"
    vagrant2.vm.network "private_network", ip: "192.168.40.21"
    vagrant2.vm.network "forwarded_port", guest: 8888, host: 8888

    vagrant2.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 2
    end
    
    vagrant2.vm.provision "shell", run: "always", inline: "/vagrant/scr.sh"
#    vagrant2.vm.provision "shell", inline: "main"    
  end
end
