Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
#  config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"
  config.proxy.http     = "http://192.168.5.9:8080"
  config.proxy.https    = "http://192.168.5.9:8080"
  config.proxy.no_proxy = "localhost,127.0.0.1"

  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.box = "ubuntu/trusty64" 
    vagrant1.vm.hostname = "vagrant1"
    vagrant1.vm.network "forwarded_port", guest: 80, host: 8080
    vagrant1.vm.network "forwarded_port", guest: 443, host: 8443

    vagrant1.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  config.vm.define "vagrant2" do |vagrant2|
    vagrant2.vm.box = "ubuntu/trusty64" 
    vagrant2.vm.hostname = "vagrant2"
    vagrant2.vm.network "forwarded_port", guest: 80, host: 8081
    vagrant2.vm.network "forwarded_port", guest: 443, host: 8444

    vagrant2.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  config.vm.define "vagrant3" do |vagrant3|
    vagrant3.vm.box = "ubuntu/trusty64" 
    vagrant3.vm.hostname = "vagrant3"
    vagrant3.vm.network "forwarded_port", guest: 80, host: 8082
    vagrant3.vm.network "forwarded_port", guest: 443, host: 8445

    vagrant3.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

end
