Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64" 
  config.vm.hostname = "testserver"
  config.proxy.http     = "http://192.168.5.9:8080"
  config.proxy.https    = "http://192.168.5.9:8080"
  config.proxy.no_proxy = "localhost,127.0.0.1"
  config.ssh.insert_key = false
  config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 2
  end
#  config.vm.network :private_network, ip: "192.168.42.10"  
end
