---
- name: Install DB
  hosts: dbserver
  become: true
  
  vars:
    mysql_rootdb_pass: 123456

  tasks:
  - name: Update system
    apt: update_cache=yes

  - name: Install dependencies
    apt: name={{ item }} state=present
    loop:
#    - php
#    - libapache2-mod-php
    - mysql-server
    - mysql-client
#    - php-mysql
    - python3-mysqldb
    - python3-dev
    - python-pip
    - libmysqlclient-dev

  - name: Install MySQL python lib
    shell: pip install MySQL-python

  - name: Start and Enable MySQL
    service: name=mysql state=started enabled=yes

  - name: Create'/root/.my.cnf'
    template:
      src: my.cnf.j2
      dest: /root/.my.cnf
      owner: root
      mode: 0600
    notify: Restart MySQL

  - name: Update root password
    mysql_user:
      name: root
      host: "{{ item }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
      password: "{{ mysql_rootdb_pass }}"
      check_implicit_admin: true
      priv: '*.*:ALL,GRANT'
    with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - localhost
    notify: Restart MySQL

  - name: Create Database
    mysql_db: name=godb state=present

  - name: Create DB User
    mysql_user:
      name: gouser
      password: 123456
      priv: 'godb.*:ALL,GRANT'
      state: present

  handlers:
  - name: Restart MySQL
    service: name=mysql state=restarted
