Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"

  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.box = "ubuntu/bionic64" 
    vagrant1.vm.hostname = "nginxserv"
    vagrant1.vm.network "private_network", ip: "192.168.40.20"
    vagrant1.vm.network "forwarded_port", guest: 80, host: 8080
    vagrant1.vm.network "forwarded_port", guest: 443, host: 8443

    vagrant1.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
  
  config.vm.provision :ansible do |ansible|
    ansible.limit = "all"
    ansible.playbook = "nginx.yml"
    ansible.inventory_path = "inventory"
  end
end
